# Generated by Django 5.2.4 on 2025-09-10 01:17

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_productimage_order_alter_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Product Details'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=3, help_text='Net price for this product', max_digits=12, verbose_name='Unit price'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_set', to='shop.product', verbose_name='Product'),
        )
    ]
