# Generated by Django 5.2.4 on 2025-09-10 03:15

import django.db.models.deletion
import modelcluster.fields
import uuid
import wagtail_site.shop.models.base.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_productpage_page_ptr_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='locale',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('translation_key', 'locale')},
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', wagtail_site.shop.models.base.fields.AutoSlugField(blank=True, editable=False, overwrite=True, populate_from='name', unique=True)),
                ('description', models.TextField(blank=True)),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
                ('pages', models.ManyToManyField(limit_choices_to={'live': True}, related_name='classifications', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Product Classification',
                'verbose_name_plural': 'Product Classifications',
                'unique_together': {('translation_key', 'locale')},
            },
        ),
        migrations.CreateModel(
            name='ProductClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.classification', verbose_name='Classification')),
                ('product', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='shop.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Classification',
                'verbose_name_plural': 'Product Classifications',
                'indexes': [models.Index(fields=['product', 'classification'], name='shop_produc_product_87067b_idx')],
            },
        ),
    ]
