# Generated by Django 5.2.4 on 2025-11-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productcategory_locale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='checkout_url',
            field=models.CharField(blank=True, help_text='URL to checkout page for this product', max_length=255, null=True, verbose_name='Checkout URL'),
        ),
    ]
