# Generated by Django 5.2.4 on 2025-12-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_checkout_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='checkout_url',
            field=models.CharField(blank=True, help_text='URL to checkout page for this product if checkout is done external.', max_length=255, null=True, verbose_name='Checkout URL'),
        ),
    ]
