# Generated by Django 4.2.3 on 2023-07-10 17:01

from apps import common
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='Enabled')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('slug', common.fields.autoslugfield.AutoSlugField(blank=True, editable=False, max_length=150, overwrite=True, populate_from='name', verbose_name='Slug')),
                ('tracking_no', models.CharField(blank=True, help_text="This ID is used to track visits to our website from this advertiser. To enable tracking, add '?wds=' to url", max_length=150, null=True, verbose_name='Advertising ID')),
            ],
            options={
                'verbose_name': 'Advertiser',
                'verbose_name_plural': 'Advertisers',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='UserSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='Enabled')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated')),
                ('query', models.CharField(db_index=True, max_length=255, verbose_name='Search term')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User search query',
                'verbose_name_plural': 'User search queries',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='Enabled')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated')),
                ('path', models.CharField(db_index=True, max_length=255, verbose_name='URL')),
                ('method', models.CharField(db_index=True, max_length=10, verbose_name='Method')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='Browser')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Session ID')),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('country', models.CharField(blank=True, max_length=3, null=True, verbose_name='Country')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('referer', models.CharField(blank=True, max_length=250, null=True, verbose_name='Referer')),
                ('advertiser_name', models.CharField(blank=True, null=True, verbose_name='Advertiser name')),
                ('advertiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_visits', to='analytics.advertiser')),
            ],
            options={
                'verbose_name': 'Page visit',
                'verbose_name_plural': 'Page visits',
                'ordering': ['-pk'],
            },
        ),
    ]
