# Generated by Django 4.2.5 on 2023-09-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagevisit',
            name='path',
            field=models.CharField(db_index=True, max_length=500, verbose_name='URL'),
        ),
    ]
