# Generated by Django 5.2 on 2025-04-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_site', '0002_sitesettings_footer_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube',
            field=models.URLField(blank=True, verbose_name='Youtube URL'),
        ),
    ]
