# Generated by Django 5.2 on 2025-04-29 16:59

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_site', '0004_webpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpagebanner',
            old_name='caption',
            new_name='heading',
        ),
        migrations.RenameField(
            model_name='webpagebanner',
            old_name='caption_position',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='webpagebanner',
            old_name='caption_size',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='intro',
        ),
        migrations.AddField(
            model_name='webpagebanner',
            name='content',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
