# Generated by Django 5.2 on 2025-04-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_site', '0005_rename_caption_webpagebanner_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpagebanner',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
