# Generated by Django 5.2.3 on 2025-07-22 13:53

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_site', '0008_alter_webpage_options_review_expire_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpage',
            name='banner',
        ),
        migrations.AddField(
            model_name='webpage',
            name='banners',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='wagtail_site.webpagebanner', verbose_name='Banners'),
        ),
    ]
