# Generated by Django 5.2.3 on 2025-07-22 21:09

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
import wagtail_site.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_site', '0009_remove_webpage_banner_webpage_banners'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='role',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='webpagebanner',
            name='button_label',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Button Label'),
        ),
        migrations.AddField(
            model_name='webpagebanner',
            name='button_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_button', to='wagtailcore.page', verbose_name='Button Link'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='DownloadsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('body', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.TextBlock', (), {'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('', 'Size'), ('h1', 'Header 1'), ('h2', 'Header 2'), ('h3', 'Header 3'), ('h4', 'Header 4'), ('h5', 'Header 5')]}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('lft', 'Left'), ('top', 'Top'), ('rt', 'Right'), ('btm', 'Bottom'), ('ctr', 'Center'), ('tpl', 'Top Left'), ('tpr', 'Top Right'), ('btl', 'Bottom Left'), ('btr', 'Bottom Right')]}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('icon', 2), ('size', 3), ('position', 4)]], {'required': False}), 6: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 7: ('wagtail.images.blocks.ImageBlock', [], {}), 8: ('wagtail.blocks.StructBlock', [[('image', 7), ('caption', 1), ('attribution', 1)]], {'required': False}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('ltr', 'Left To Right'), ('rtl', 'Right To Left')], 'help_text': 'Direction of the content. Left to right means text is displayed on the left and image on the right.'}), 10: ('wagtail.blocks.StructBlock', [[('heading', 5), ('content', 6), ('image', 8), ('direction', 9)]], {})})),
                ('documents', wagtail.fields.StreamField([('document', 0)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {})}, null=True)),
                ('banners', modelcluster.fields.ParentalManyToManyField(blank=True, to='wagtail_site.webpagebanner', verbose_name='Banners')),
            ],
            options={
                'verbose_name': 'Downloads Page',
                'verbose_name_plural': 'Downloads Pages',
            },
            bases=(wagtail_site.mixins.DefaultTemplatesMixin, 'wagtailcore.page', models.Model),
        ),
    ]
