# Generated by Django 5.2.3 on 2025-07-22 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_site', '0011_remove_downloadspage_banners_remove_webpage_banners_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagebanner',
            name='banner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wagtail_site.webpagebanner'),
        ),
    ]
