# Generated by Django 5.2.3 on 2025-07-22 22:08

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_site', '0012_alter_pagebanner_banner'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webpagebanner',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterUniqueTogether(
            name='webpagebanner',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='webpagebanner',
            name='page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='webpagebanner',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.DeleteModel(
            name='PageBanner',
        ),
        migrations.RemoveField(
            model_name='webpagebanner',
            name='expire_at',
        ),
        migrations.RemoveField(
            model_name='webpagebanner',
            name='expired',
        ),
        migrations.RemoveField(
            model_name='webpagebanner',
            name='first_published_at',
        ),
        migrations.RemoveField(
            model_name='webpagebanner',
            name='go_live_at',
        ),
        migrations.RemoveField(
            model_name='webpagebanner',
            name='has_unpublished_changes',
        ),
        migrations.RemoveField(
            model_name='webpagebanner',
            name='last_published_at',
        ),
        migrations.RemoveField(
            model_name='webpagebanner',
            name='latest_revision',
        ),
        migrations.RemoveField(
            model_name='webpagebanner',
            name='live',
        ),
        migrations.RemoveField(
            model_name='webpagebanner',
            name='live_revision',
        ),
        migrations.RemoveField(
            model_name='webpagebanner',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='webpagebanner',
            name='translation_key',
        ),
    ]
