# Generated by Django 5.2.3 on 2025-07-23 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_site', '0013_alter_webpagebanner_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DownloadsPage',
        ),
    ]
