# Generated by Django 5.2.10 on 2026-01-07 22:58

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_site', '0014_delete_downloadspage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='body',
            field=wagtail.fields.StreamField([('body', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.TextBlock', (), {'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('', 'Size'), ('h1', 'Header 1'), ('h2', 'Header 2'), ('h3', 'Header 3'), ('h4', 'Header 4'), ('h5', 'Header 5')]}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('lft', 'Left'), ('top', 'Top'), ('rt', 'Right'), ('btm', 'Bottom'), ('ctr', 'Center'), ('tpl', 'Top Left'), ('tpr', 'Top Right'), ('btl', 'Bottom Left'), ('btr', 'Bottom Right')]}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('icon', 2), ('size', 3), ('position', 4)]], {'required': False}), 6: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 7: ('wagtail.images.blocks.ImageBlock', [], {}), 8: ('wagtail.blocks.StructBlock', [[('image', 7), ('caption', 1), ('attribution', 1)]], {'required': False}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('ltr', 'Left To Right'), ('rtl', 'Right To Left')], 'help_text': 'Direction of the content. Left to right means text is displayed on the left and image on the right.'}), 10: ('wagtail.blocks.StructBlock', [[('heading', 5), ('content', 6), ('embed', 2), ('image', 8), ('direction', 9)]], {})}),
        ),
    ]
