# Generated by Django 5.2.10 on 2026-01-09 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_site', '0015_alter_webpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_site.pageform', verbose_name='Form'),
        ),
    ]
